# Arbeitsblatt 1

In [ ]:
#Imports der benötigten Pakete
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
#Einlesen der CSV-Datei
data = pd.read_csv('DABI2_Projekt1.csv')

       Unnamed: 0 rate                     DateTime      KWH  meters
0               0  Std  2011-11-23 09:00:00.0000000    0.355       1
1               1  Std  2011-11-23 09:30:00.0000000    0.414       1
2               2  Std  2011-11-23 10:00:00.0000000    0.698       4
3               3  Std  2011-11-23 10:30:00.0000000    0.455       4
4               4  Std  2011-11-23 11:00:00.0000000    0.670       5
...           ...  ...                          ...      ...     ...
80685       80685  ToU  2014-02-27 22:00:00.0000000  302.767    1026
80686       80686  ToU  2014-02-27 22:30:00.0000000  286.752    1026
80687       80687  ToU  2014-02-27 23:00:00.0000000  254.521    1026
80688       80688  ToU  2014-02-27 23:30:00.0000000  211.434    1026
80689       80689  ToU  2014-02-28 00:00:00.0000000  356.944    2052

[80690 rows x 5 columns]

In [ ]:
# Erster Blick auf die Daten
data.head()
#Daten bereinigen/in das richtige Format bringen
data['DateTime'] = pd.to_datetime(data['DateTime'], format='mixed')

       Unnamed: 0 rate            DateTime      KWH  meters
0               0  Std 2011-11-23 09:00:00    0.355       1
1               1  Std 2011-11-23 09:30:00    0.414       1
2               2  Std 2011-11-23 10:00:00    0.698       4
3               3  Std 2011-11-23 10:30:00    0.455       4
4               4  Std 2011-11-23 11:00:00    0.670       5
...           ...  ...                 ...      ...     ...
80685       80685  ToU 2014-02-27 22:00:00  302.767    1026
80686       80686  ToU 2014-02-27 22:30:00  286.752    1026
80687       80687  ToU 2014-02-27 23:00:00  254.521    1026
80688       80688  ToU 2014-02-27 23:30:00  211.434    1026
80689       80689  ToU 2014-02-28 00:00:00  356.944    2052

[80690 rows x 5 columns]

In [ ]:
#Aufgabe 1: Prüfen Sie den Energieverbrauch auf Trends und Periodizität, trennen Sie die verschiedenen Bestandteile und visualisieren Sie sie geeigneter Weise.